### ISSUE TITLE
Issues with first boot

### ISSUE THREAD

**Issue by jonatan-holmgren** [izer-xyz/3cx-docker#16] opened 2022-10-09 06:41 UTC
```
Failed to create /init.scope control group: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```
What do I do?

**Comment by sinegar** [comment] 2022-10-10 08:37
That looks like a problem with systemd. Have you mounted cgroup ( `-v    /sys/fs/cgroup:/sys/fs/cgroup:ro `)?

How do you start the container? Would you share the docker run command line or the docker compose file?

You can have a look at the readme Troubleshooting/ 1.

**Comment by etam** [comment] 2022-10-17 20:16
duplicate of #4 ?

**Comment by sinegar** [comment] 2022-10-18 00:10
Yes, it seems like a systemd issue which I can’t help.

**Comment by sinegar** [comment] 2022-12-02 04:43
I had a similar issue with the github action that I use to build the container and adding `--cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw` to the command line. `cgroupns` might not work with docker compose.

**Comment by jonatan-holmgren** [comment] 2022-12-12 19:34
Worked, closing.

**Closed as completed** 2022-12-12 19:34 UTC
